version: '3.5'

services:
  instrument:
    build:
      context: ./serial-socket
      dockerfile: instruments/${SOCKET_HOST}/Dockerfile
    image: ${SOCKET_HOST}
    container_name: ${SOCKET_HOST}
    networks:
      - equipment
    ports:
      - "${SOCKET_PORT}:${SOCKET_PORT}"
    devices:
      - "${SERIAL_PORT}:/dev/ttyACM0"
    restart: unless-stopped
    env_file:
      - .env
    command: ["--instrument_port", "${SERIAL_PORT}", "--socket_ip", "${SOCKET_HOST}", "--socket_port", "${SOCKET_PORT}", "--host", "${HOST}"]
  socket-mqtt:
    build:
      context: ./socket-mqtt
      dockerfile: Dockerfile
    image: socket-mqtt
    container_name: socket-mqtt
    env_file:
      - .env
    command: ["--socket_host", "${SOCKET_HOST}", "--socket_port", "${SOCKET_PORT}", "--mqtt_broker", "${MQTT_BROKER}", "--group_id", "${GROUP_ID}", "--device_id", "${DEVICE_ID}"]
    networks:
      - equipment
    restart: unless-stopped
    depends_on:
      - instrument


networks:
  equipment:
    ipam:
      driver: default
      config:
        - subnet: 172.19.5.1/27
