version: '3.5'

services:
  bronkhorst:
    build:
      context: .
      dockerfile: ./serial-socket/instruments/bronkhorst/Dockerfile
    image: bronkhorst
    container_name: bronkhorst
    networks:
      - equipment      
    ports:
      - "5007:5007"
    devices:
      - "/dev/ttyUSB0:/dev/ttyUSB0"
    restart: unless-stopped

networks:
  equipment:
    ipam:
      driver: default
      config:
        - subnet: 172.19.5.1/27
