version: '3.5'
services:

  socket:
    build: ./serial-socket
    image: serial-socket
    container_name: serial-socket
    networks:
      - equipment      
    ports:
      - "5007:5007"
    devices:
      - "/dev/ttyUSB0:/dev/ttyUSB0"
    restart: unless-stopped

networks:
  equipment:
    ipam:
      driver: default
      config:
        - subnet: 172.19.0.1/27
