version: '3.5'

services:
  instrument:
    build:
      context: ./serial-socket
      dockerfile: instruments/${SOCKET_HOST}/Dockerfile
    image: ${SOCKET_HOST}
    container_name: ${SOCKET_HOST}
    networks:
      - equipment
    ports:
      - "${SOCKET_PORT}:${SOCKET_PORT}"
        #    devices:
        #      - "${SERIAL_PORT}:/dev/ttyUSB0"
    restart: unless-stopped
    env_file:
      - .env
  socket-mqtt:
    build:
      context: ./socket-mqtt
      dockerfile: Dockerfile
    image: socket-mqtt
    container_name: socket-mqtt
    env_file:
      - .env
    networks:
      - equipment
    restart: unless-stopped
    depends_on:
      - instrument


networks:
  equipment:
    ipam:
      driver: default
      config:
        - subnet: 172.19.5.1/27
